/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProcesarTurnoController;
import java.awt.Color;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import model.TipoTramite;

/**
 *
 * @author Ariel
 */
public class PanelProcesarTurno03 extends javax.swing.JPanel implements InterfacePanel {

    private final ValidadorDeCampos validador;

    private final ProcesarTurnoController controlador;

    /**
     * Creates new form PanelEmpresa
     *
     * @param controlador
     */
    public PanelProcesarTurno03(ProcesarTurnoController controlador) {

        initComponents();
        validador = new ValidadorDeCampos();
        habilitarTodosLosBotones(true);
        this.controlador = controlador;

        cargarTipoDeTramites();

        this.jpb_estado_procesarTurno.setStringPainted(true);
        this.jpb_estado_procesarTurno.setString("Seleccionar un TIPO TRAMITE");
        this.jpb_estado_procesarTurno.setValue(45);
        this.jpb_estado_procesarTurno.setForeground(new Color(220, 118, 51));

        this.jlbl_titulo.setBackground(Color.BLACK);
        this.jlbl_titulo.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProgreso = new javax.swing.JPanel();
        jpb_estado_procesarTurno = new javax.swing.JProgressBar();
        jlbl_titulo = new javax.swing.JLabel();
        jPanel_Contenido = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcb_tipoTramite = new javax.swing.JComboBox<>();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_cancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(950, 750));
        setMinimumSize(new java.awt.Dimension(950, 750));
        setPreferredSize(new java.awt.Dimension(950, 750));

        jlbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_titulo.setText("PROCESAR TURNO");

        javax.swing.GroupLayout jPanelProgresoLayout = new javax.swing.GroupLayout(jPanelProgreso);
        jPanelProgreso.setLayout(jPanelProgresoLayout);
        jPanelProgresoLayout.setHorizontalGroup(
            jPanelProgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProgresoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpb_estado_procesarTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelProgresoLayout.setVerticalGroup(
            jPanelProgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProgresoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jpb_estado_procesarTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_Contenido.setMaximumSize(new java.awt.Dimension(930, 460));
        jPanel_Contenido.setMinimumSize(new java.awt.Dimension(930, 460));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("TIPO TRAMITE");

        javax.swing.GroupLayout jPanel_ContenidoLayout = new javax.swing.GroupLayout(jPanel_Contenido);
        jPanel_Contenido.setLayout(jPanel_ContenidoLayout);
        jPanel_ContenidoLayout.setHorizontalGroup(
            jPanel_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ContenidoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcb_tipoTramite, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_ContenidoLayout.setVerticalGroup(
            jPanel_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ContenidoLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel_ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcb_tipoTramite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(347, Short.MAX_VALUE))
        );

        jbtn_siguiente.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtn_siguiente.setText("SIGUIENTE");
        jbtn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_siguienteActionPerformed(evt);
            }
        });

        jbtn_cancelar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtn_cancelar.setText("CANCELAR");
        jbtn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_siguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelProgreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jbtn_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelarActionPerformed
        //Inhabilita Botones
        habilitarTodosLosBotones(false);

        //limpia todos los campos
        limpiarTodosLosCampos();

        //Habilita el Arbol de seleccion
        JFramePrincipal.getArbolModulos().setEnabled(true);
        JFramePrincipal.getjPanelContenido().removeAll();
        JFramePrincipal.getjPanelContenido().repaint();
    }//GEN-LAST:event_jbtn_cancelarActionPerformed

    private void jbtn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_siguienteActionPerformed
        TipoTramite nuevoTipoTramite = (TipoTramite) this.jcb_tipoTramite.getSelectedItem();
        this.controlador.getNuevoTurno().setUnTipoTramite(nuevoTipoTramite);

        //Se crea el Panel Emplesa    
        PanelProcesarTurno04 unPaneProcesarTurno04 = new PanelProcesarTurno04(this.controlador);
        unPaneProcesarTurno04.setSize(950, 750);
        unPaneProcesarTurno04.setLocation(0, 0);
        unPaneProcesarTurno04.setVisible(true);

        //JFramePrincipal.modificarPanelContenido(unPanelProcesarTurno02);
        JFramePrincipal.getjPanelContenido().removeAll();
        JFramePrincipal.getjPanelContenido().add(unPaneProcesarTurno04);
        JFramePrincipal.getjPanelContenido().repaint();
        JFramePrincipal.getjPanelContenido().validate();

    }//GEN-LAST:event_jbtn_siguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelProgreso;
    private javax.swing.JPanel jPanel_Contenido;
    private javax.swing.JButton jbtn_cancelar;
    private javax.swing.JButton jbtn_siguiente;
    private javax.swing.JComboBox<String> jcb_tipoTramite;
    private javax.swing.JLabel jlbl_titulo;
    private javax.swing.JProgressBar jpb_estado_procesarTurno;
    // End of variables declaration//GEN-END:variables

    @Override
    public void habilitarTodosLosCampos(boolean estado) {
        //inhabilita campos
    }

    @Override
    public void limpiarTodosLosCampos() {
    }

    @Override
    public void habilitarTodosLosBotones(boolean estado) {
        this.validador.habilitarBoton(estado, jbtn_cancelar, Color.red, Color.WHITE, null, null);
        this.validador.habilitarBoton(estado, this.jbtn_siguiente, new Color(30, 132, 73), Color.WHITE, null, null);
    }

    /**
     * Carga las Areas el el JComboBox area
     */
    public void cargarTipoDeTramites() {
        DefaultComboBoxModel mdl = new DefaultComboBoxModel((Vector) this.controlador.buscarTodosLosTramitesPorArea(this.controlador.getNuevoTurno().getUnDepartamentoB()));
        this.jcb_tipoTramite.setModel(mdl);
    }
}
