/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.LoginController;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import model.TipoUsuario;

/**
 *
 * @author Ariel
 */
public class JFramePrincipal extends javax.swing.JFrame {

    private TipoUsuario tipoUsuario = null;
    private final LoginController controlador;

    private PanelOrganismo unPanelEmpresa;
    private PanelPersona unPanelPersona;
    private PanelEmpleado unPanelEmpleado;
    private PanelUsuario unPanelUsuario;
    private PanelProcesarTurno01 unPanelProcesarTurno01;
    private PanelProcesarTramite01 unPanelProcesarTramite01;

    private final ValidadorDeCampos validador;

    /**
     * captura la seleccion en el arbol
     */
    String captura = null;

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        //Carga Icono de la empresa
        try {
            //Icono de la aplicacion
            setIconImage(new ImageIcon(getClass().getResource("../imagenes/logo.png")).getImage());

        } catch (Exception e) {
        }
        initComponents();
        this.setSize(1200, 750);
        this.controlador = new LoginController();
        validador = new ValidadorDeCampos();

        this.validador.habilitarBoton(true, this.jbtn_almorzar, Color.BLUE, Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_finalizarJornadaLaboral, Color.BLUE, Color.WHITE, null, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneArbol = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbl_usuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlbl_TipoUsuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlbl_puesto = new javax.swing.JLabel();
        jbtn_almorzar = new javax.swing.JButton();
        jbtn_finalizarJornadaLaboral = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1330, 850));
        setMinimumSize(new java.awt.Dimension(1330, 850));
        setPreferredSize(new java.awt.Dimension(1330, 850));
        setResizable(false);

        jPanelArbol.setBackground(new java.awt.Color(255, 153, 51));
        jPanelArbol.setMaximumSize(new java.awt.Dimension(350, 750));
        jPanelArbol.setMinimumSize(new java.awt.Dimension(350, 750));
        jPanelArbol.setPreferredSize(new java.awt.Dimension(350, 750));

        jScrollPaneArbol.setAlignmentX(0.0F);
        jScrollPaneArbol.setAlignmentY(0.0F);
        jScrollPaneArbol.setMaximumSize(new java.awt.Dimension(350, 750));
        jScrollPaneArbol.setMinimumSize(new java.awt.Dimension(350, 750));
        jScrollPaneArbol.setPreferredSize(new java.awt.Dimension(350, 750));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("El Porvenir");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Administración General");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Organismo");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Personas");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Empleados");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Usuarios");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Gestión de Turnos");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Asignar Turno");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Gestion de Tramite");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Procesar Tramite");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        arbolModulos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbolModulos.setAlignmentX(0.0F);
        arbolModulos.setAlignmentY(0.0F);
        arbolModulos.setMaximumSize(new java.awt.Dimension(330, 750));
        arbolModulos.setMinimumSize(new java.awt.Dimension(330, 750));
        arbolModulos.setName(""); // NOI18N
        arbolModulos.setPreferredSize(new java.awt.Dimension(330, 750));
        arbolModulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolModulosMouseClicked(evt);
            }
        });
        jScrollPaneArbol.setViewportView(arbolModulos);

        javax.swing.GroupLayout jPanelArbolLayout = new javax.swing.GroupLayout(jPanelArbol);
        jPanelArbol.setLayout(jPanelArbolLayout);
        jPanelArbolLayout.setHorizontalGroup(
            jPanelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArbolLayout.createSequentialGroup()
                .addComponent(jScrollPaneArbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelArbolLayout.setVerticalGroup(
            jPanelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArbolLayout.createSequentialGroup()
                .addComponent(jScrollPaneArbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelContenido.setBackground(new java.awt.Color(153, 255, 204));
        jPanelContenido.setAlignmentX(0.0F);
        jPanelContenido.setAlignmentY(0.0F);
        jPanelContenido.setAutoscrolls(true);
        jPanelContenido.setMaximumSize(new java.awt.Dimension(950, 750));
        jPanelContenido.setMinimumSize(new java.awt.Dimension(950, 750));
        jPanelContenido.setName(""); // NOI18N
        jPanelContenido.setPreferredSize(new java.awt.Dimension(950, 750));

        javax.swing.GroupLayout jPanelContenidoLayout = new javax.swing.GroupLayout(jPanelContenido);
        jPanelContenido.setLayout(jPanelContenidoLayout);
        jPanelContenidoLayout.setHorizontalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jPanelContenidoLayout.setVerticalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setMaximumSize(new java.awt.Dimension(1342, 60));
        jPanel3.setMinimumSize(new java.awt.Dimension(1342, 60));
        jPanel3.setPreferredSize(new java.awt.Dimension(1342, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("USUARIO:");

        jlbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("TIPO USUARIO");

        jlbl_TipoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("TIPO EMPLEADO");

        jlbl_puesto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jbtn_almorzar.setText("Almorzar");
        jbtn_almorzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_almorzarActionPerformed(evt);
            }
        });

        jbtn_finalizarJornadaLaboral.setText("Finalizar Jornada Laboral");
        jbtn_finalizarJornadaLaboral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_finalizarJornadaLaboralActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jlbl_TipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlbl_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_almorzar)
                .addGap(18, 18, 18)
                .addComponent(jbtn_finalizarJornadaLaboral)
                .addGap(110, 110, 110))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn_almorzar)
                        .addComponent(jbtn_finalizarJornadaLaboral))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jlbl_puesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addComponent(jlbl_TipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbl_usuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelArbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelArbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arbolModulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolModulosMouseClicked

        if (arbolModulos.isEnabled()) {
            TreePath tp = arbolModulos.getPathForLocation(evt.getX(), evt.getY());
            if (tp != null) {
                captura = arbolModulos.getSelectionPath().toString();
                /*Intentanmos validar si la cadena equivale a vacio.
                Si ejecutamos nos daremos cuenta que esto
                genera una excepciòn ya que la cadena es nula*/

                if (captura.equals("[" + LoginController.getInstanceMunicipalidad().getNombre() + ", Administración General, Organismo]")) {

                    habilitarArbol(false);

                    //Se crea el Panel Emplesa
                    this.unPanelEmpresa = new PanelOrganismo();
                    this.unPanelEmpresa.setSize(950, 750);
                    this.unPanelEmpresa.setVisible(true);

                    this.jPanelContenido.add(this.unPanelEmpresa);
                    this.unPanelEmpresa.validate();

                }

                if (captura.equals("[" + LoginController.getInstanceMunicipalidad().getNombre() + ", Administración General, Personas]")) {

                    habilitarArbol(false);

                    //Se crea el Panel Emplesa
                    this.unPanelPersona = new PanelPersona();
                    this.unPanelPersona.setSize(950, 750);
                    this.unPanelPersona.setVisible(true);

                    this.jPanelContenido.add(this.unPanelPersona);

                    this.unPanelPersona.validate();
                }
                if (captura.equals("[" + LoginController.getInstanceMunicipalidad().getNombre() + ", Administración General, Empleados]")) {

                    habilitarArbol(false);

                    //Se crea el Panel Operador
                    this.unPanelEmpleado = new PanelEmpleado();
                    this.unPanelEmpleado.setSize(950, 750);
                    this.unPanelEmpleado.setVisible(true);

                    this.jPanelContenido.add(this.unPanelEmpleado);

                    this.unPanelEmpleado.validate();
                }

                if (captura.equals("[" + LoginController.getInstanceMunicipalidad().getNombre() + ", Administración General, Usuarios]")) {

                    habilitarArbol(false);

                    //Se crea el Panel Emplesa
                    this.unPanelUsuario = new PanelUsuario();
                    this.unPanelUsuario.setSize(950, 750);
                    this.unPanelUsuario.setVisible(true);

                    this.jPanelContenido.add(this.unPanelUsuario);

                    this.unPanelUsuario.validate();
                }

                if (captura.equals("[" + LoginController.getInstanceMunicipalidad().getNombre() + ", Gestión de Turnos, Asignar Turno]")) {

                    habilitarArbol(false);

                    //Se crea el Panel Emplesa
                    this.unPanelProcesarTurno01 = new PanelProcesarTurno01();
                    this.unPanelProcesarTurno01.setSize(950, 750);
                    this.unPanelProcesarTurno01.setVisible(true);

                    this.jPanelContenido.add(this.unPanelProcesarTurno01);

                    this.unPanelProcesarTurno01.validate();
                }

                if (captura.equals("[" + LoginController.getInstanceMunicipalidad().getNombre() + ", Gestion de Tramite, Procesar Tramite]")) {

                    habilitarArbol(false);

                    //Se crea el Panel Emplesa
                    this.unPanelProcesarTramite01 = new PanelProcesarTramite01();
                    this.unPanelProcesarTramite01.setSize(950, 750);
                    this.unPanelProcesarTramite01.setVisible(true);

                    this.jPanelContenido.add(this.unPanelProcesarTramite01);

                    this.unPanelProcesarTramite01.validate();
                }

            }
        }
    }//GEN-LAST:event_arbolModulosMouseClicked

    private void jbtn_almorzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_almorzarActionPerformed

        int opcion = JOptionPane.showConfirmDialog(null, "¿Desea confirmar el almuerzo?", "Alerta!", JOptionPane.YES_NO_OPTION);

        if (opcion == 0) {
            if (controlador.almorzar()) {
                System.out.println("Si puede");
                System.exit(0);
            } else {
                this.validador.habilitarBoton(false, this.jbtn_almorzar, Color.BLUE, Color.WHITE, null, null);
                this.validador.habilitarBoton(false, this.jbtn_finalizarJornadaLaboral, Color.BLUE, Color.WHITE, null, null);
                System.out.println("No puede");
            }
        }
    }//GEN-LAST:event_jbtn_almorzarActionPerformed

    private void jbtn_finalizarJornadaLaboralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_finalizarJornadaLaboralActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Desea confirmar el fin de la Jornada laboral?", "Alerta!", JOptionPane.YES_NO_OPTION);

        if (opcion == 0) {
            if (controlador.finalizarJornadaLaboral()) {
                System.out.println("finalizado");
                System.exit(0);
            } else {

                System.out.println("No puede");
                this.validador.habilitarBoton(false, this.jbtn_almorzar, Color.BLUE, Color.WHITE, null, null);
                this.validador.habilitarBoton(false, this.jbtn_finalizarJornadaLaboral, Color.BLUE, Color.WHITE, null, null);
            }
        }
    }//GEN-LAST:event_jbtn_finalizarJornadaLaboralActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JTree arbolModulos = new javax.swing.JTree();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    public static final javax.swing.JPanel jPanelArbol = new javax.swing.JPanel();
    public static final javax.swing.JPanel jPanelContenido = new javax.swing.JPanel();
    private javax.swing.JScrollPane jScrollPaneArbol;
    private javax.swing.JButton jbtn_almorzar;
    private javax.swing.JButton jbtn_finalizarJornadaLaboral;
    private javax.swing.JLabel jlbl_TipoUsuario;
    private javax.swing.JLabel jlbl_puesto;
    private javax.swing.JLabel jlbl_usuario;
    // End of variables declaration//GEN-END:variables

    public void arranca() {
        this.tipoUsuario = LoginController.getInstanceUsuario().getTipoUsuario();

        if (this.tipoUsuario != null) {

            if (this.tipoUsuario.getDescripcion().equals("Persona")) {
                JOptionPane.showMessageDialog(this, "Los Cliente solo pueden ingresar por la web");
                System.exit(0);
            }

            if (this.tipoUsuario.getDescripcion().equals("Administrador")) {
                //Si el usuario posee un empleado asociado
                if (LoginController.getInstanceUsuario().getUnOperador() != null) {
                    cargarArbol(1);
                    //Uso del Singleton creado en el Login
                    this.jlbl_usuario.setText(LoginController.getInstanceUsuario().getNombre());
                    this.jlbl_TipoUsuario.setText(LoginController.getInstanceUsuario().getTipoUsuario().getDescripcion());
                    this.jlbl_puesto.setText(LoginController.getInstanceUsuario().getUnOperador().getUnTipoOperador().getDescripcion());

                    jPanelContenido.repaint();
                    setLocationRelativeTo(null);// centra la ventana en la pantalla
                    setVisible(true);// visualiza la ventana
                    //default title and icon
                }
            }

            if (this.tipoUsuario.getDescripcion().equals("Operador")) {

                //Si el usuario posee un empleado asociado
                if (LoginController.getInstanceUsuario().getUnOperador() != null) {

                    if (LoginController.getInstanceUsuario().getUnOperador().getUnTipoOperador().getDescripcion().equals("Operador de Mesa de Entrada")) {
                        cargarArbol(2);
                    }

                    if (LoginController.getInstanceUsuario().getUnOperador().getUnTipoOperador().getDescripcion().equals("Operador de Tramites de DNI y Pasaporte")) {
                        cargarArbol(3);
                    }

                    if (LoginController.getInstanceUsuario().getUnOperador().getUnTipoOperador().getDescripcion().equals("Operador de Inscripciones")) {
                        cargarArbol(3);
                    }

                    //Uso del Singleton creado en el Login
                    this.jlbl_usuario.setText(LoginController.getInstanceUsuario().getNombre());
                    this.jlbl_TipoUsuario.setText(LoginController.getInstanceUsuario().getTipoUsuario().getDescripcion());
                    this.jlbl_puesto.setText(LoginController.getInstanceUsuario().getUnOperador().getUnTipoOperador().getDescripcion());

                    jPanelContenido.repaint();
                    setLocationRelativeTo(null);// centra la ventana en la pantalla
                    setVisible(true);// visualiza la ventana
                    //default title and icon
                } else {
                    JOptionPane.showMessageDialog(this, "El usuario es de tipo empleado, pero no tiene empleado asociado. Contacte con el Administrador");
                    System.exit(0);
                }
            }
        }
    }

    /**
     * Se llama desde cualquier lugar de la aplicación y bloqueara o habilitara
     * el arbol
     *
     * @param estado
     */
    private void habilitarArbol(boolean estado) {
        this.arbolModulos.setEnabled(estado);
        this.jPanelArbol.setEnabled(estado);
        this.jPanelArbol.repaint();
        this.jPanelArbol.validate();

        this.jPanelContenido.removeAll();
        this.jPanelContenido.repaint();
        this.jPanelContenido.validate();

        this.repaint();
        this.validate();
    }

    public static javax.swing.JPanel getjPanelArbol() {
        return jPanelArbol;
    }

    public static javax.swing.JPanel getjPanelContenido() {
        return jPanelContenido;
    }

    public static javax.swing.JTree getArbolModulos() {
        return arbolModulos;
    }

    private void cargarArbol(int permiso) {

        //raiz
        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode(LoginController.getInstanceMunicipalidad().getNombre());

        //nivel 1
        DefaultMutableTreeNode lvl_1a = new DefaultMutableTreeNode("Administración General");

        DefaultMutableTreeNode lvl_1b = new DefaultMutableTreeNode("Gestión de Turnos");

        DefaultMutableTreeNode lvl_1c = new DefaultMutableTreeNode("Gestion de Tramite");

        //nivel 2
        DefaultMutableTreeNode lvl_1aa = new DefaultMutableTreeNode("Organismo");
        DefaultMutableTreeNode lvl_1ab = new DefaultMutableTreeNode("Personas");
        DefaultMutableTreeNode lvl_1ac = new DefaultMutableTreeNode("Empleados");
        DefaultMutableTreeNode lvl_1ad = new DefaultMutableTreeNode("Usuarios");

        DefaultMutableTreeNode lvl_1ba = new DefaultMutableTreeNode("Asignar Turno");

        DefaultMutableTreeNode lvl_1ca = new DefaultMutableTreeNode("Procesar Tramite");

        lvl_1a.add(lvl_1aa);
        lvl_1a.add(lvl_1ab);
        lvl_1a.add(lvl_1ac);
        lvl_1a.add(lvl_1ad);

        lvl_1b.add(lvl_1ba);

        lvl_1c.add(lvl_1ca);

        if (permiso == 1) {
            raiz.add(lvl_1a);
            raiz.add(lvl_1b);
            raiz.add(lvl_1c);
        }

        if (permiso == 2) {
            raiz.add(lvl_1b);
        }

        if (permiso == 3) {
            raiz.add(lvl_1c);
        }

        arbolModulos.setModel(new javax.swing.tree.DefaultTreeModel(raiz));

    }

}
