/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.OperadorController;
import dao.exceptions.NonexistentEntityException;
import java.awt.Color;
import java.awt.Rectangle;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Departamento;
import model.Operador;
import model.TipoOperador;
import view.resources.TablaEmpleadoModelListener;
import view.resources.TablaOperadorModelo;

/**
 *
 * @author Ariel
 */
public class PanelEmpleado extends javax.swing.JPanel implements InterfacePanel {

    private final ValidadorDeCampos validador;

    //variables de tabla
    private final TablaOperadorModelo tablaEmpleadoModelo;

    //variables de comboBox
    private final DefaultComboBoxModel tipoEmpleadoModel;
    
    //variables de comboBox
    private final DefaultComboBoxModel tipoDepartamentoModel;

    private final OperadorController controlador;
    private Operador operadorSeleccionado;

    private final List<Operador> operadores;

    private String crud;

    /**
     * Creates new form PanelPersona
     */
    public PanelEmpleado() {
        //JTable vacio
        this.tablaEmpleadoModelo = new TablaOperadorModelo();
        this.validador = new ValidadorDeCampos();
        //JComboBox vacio
        this.tipoEmpleadoModel = new DefaultComboBoxModel();
        this.tipoDepartamentoModel = new DefaultComboBoxModel();
        this.crud = "";

        this.operadores = new ArrayList<>();
        initComponents();
        habilitarTodosLosBotones(false);
        this.validador.habilitarBoton(true, this.jbtn_volver, Color.red, Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(false, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);

        habilitarTodosLosCampos(false);

        //iniciar el controlador de esta vista
        this.controlador = new OperadorController();
        setSize(800, 600);

        //agrega escuchadores de las tablas
        this.jtb_empleado.getSelectionModel().addListSelectionListener(new TablaEmpleadoModelListener(this));

        limpiarTodosLosCampos();

        this.validador.LimitarCaracteres(this.jtf_dni, 8);
        this.validador.validarSoloNumero(this.jtf_dni);
        this.validador.LimitarCaracteres(this.jtf_buscarEmpleado, 8);
        this.validador.validarSoloNumero(this.jtf_buscarEmpleado);

        this.validador.validarSoloLetras(jtf_nombre);
        this.validador.LimitarCaracteres(this.jtf_nombre, 30);
        this.validador.validarSoloLetras(jtf_apellido);
        this.validador.LimitarCaracteres(this.jtf_apellido, 30);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_crud = new javax.swing.JPanel();
        jScrollPaneTabla = new javax.swing.JScrollPane();
        jtb_empleado = new javax.swing.JTable();
        jbtn_listar = new javax.swing.JButton();
        jbtn_agregar = new javax.swing.JButton();
        jtf_buscarEmpleado = new javax.swing.JTextField();
        jPanel_datos = new javax.swing.JPanel();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtf_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtf_apellido = new javax.swing.JTextField();
        jtf_dni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcb_tipoEmpleado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jbtn_modificar = new javax.swing.JButton();
        jbtn_aceptar = new javax.swing.JButton();
        jlbl_mensaje = new javax.swing.JLabel();
        jlbl_alertaNombre = new javax.swing.JLabel();
        jlbl_alertaApellido = new javax.swing.JLabel();
        jlbl_alertaDNI = new javax.swing.JLabel();
        jlbl_alertaTipoPersona = new javax.swing.JLabel();
        jcb_area = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jbtn_volver = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(950, 750));
        setMinimumSize(new java.awt.Dimension(950, 750));
        setPreferredSize(new java.awt.Dimension(950, 750));

        jScrollPaneTabla.setMaximumSize(new java.awt.Dimension(950, 750));
        jScrollPaneTabla.setMinimumSize(new java.awt.Dimension(950, 750));
        jScrollPaneTabla.setPreferredSize(new java.awt.Dimension(950, 750));

        jtb_empleado.setModel(tablaEmpleadoModelo);
        jScrollPaneTabla.setViewportView(jtb_empleado);

        jbtn_listar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn_listar.setText("LISTAR POR DNI");
        jbtn_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_listarActionPerformed(evt);
            }
        });

        jbtn_agregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn_agregar.setText("AGREGAR");
        jbtn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregarActionPerformed(evt);
            }
        });

        jtf_buscarEmpleado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtf_buscarEmpleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_buscarEmpleadoFocusGained(evt);
            }
        });
        jtf_buscarEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_buscarEmpleadoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel_crudLayout = new javax.swing.GroupLayout(jPanel_crud);
        jPanel_crud.setLayout(jPanel_crudLayout);
        jPanel_crudLayout.setHorizontalGroup(
            jPanel_crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_crudLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel_crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 910, Short.MAX_VALUE)
                    .addGroup(jPanel_crudLayout.createSequentialGroup()
                        .addComponent(jbtn_listar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38)
                        .addComponent(jtf_buscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_crudLayout.setVerticalGroup(
            jPanel_crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_crudLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPaneTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 230, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_buscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jbtn_eliminar.setText("ELIMINAR");
        jbtn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_eliminarActionPerformed(evt);
            }
        });

        jbtn_cancelar.setText("CANCELAR");
        jbtn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("NOMBRE");

        jtf_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("APELLIDO");

        jtf_apellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtf_dni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("TIPO EMPLEADO");

        jcb_tipoEmpleado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcb_tipoEmpleado.setModel(tipoEmpleadoModel);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("DNI");

        jbtn_modificar.setText("MODIFICAR");
        jbtn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_modificarActionPerformed(evt);
            }
        });

        jbtn_aceptar.setText("ACEPTAR");
        jbtn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_aceptarActionPerformed(evt);
            }
        });

        jlbl_mensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbl_mensaje.setForeground(new java.awt.Color(255, 0, 0));

        jlbl_alertaNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlbl_alertaApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlbl_alertaDNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlbl_alertaTipoPersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jcb_area.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcb_area.setModel(tipoDepartamentoModel);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("AREA");

        javax.swing.GroupLayout jPanel_datosLayout = new javax.swing.GroupLayout(jPanel_datos);
        jPanel_datos.setLayout(jPanel_datosLayout);
        jPanel_datosLayout.setHorizontalGroup(
            jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_datosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
            .addGroup(jPanel_datosLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbl_mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                    .addComponent(jcb_area, javax.swing.GroupLayout.Alignment.TRAILING, 0, 479, Short.MAX_VALUE)
                    .addComponent(jcb_tipoEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtf_apellido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_dni))
                .addGap(18, 18, 18)
                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl_alertaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_alertaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_alertaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_alertaTipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_datosLayout.setVerticalGroup(
            jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_datosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_datosLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_datosLayout.createSequentialGroup()
                        .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel_datosLayout.createSequentialGroup()
                                .addComponent(jlbl_alertaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbl_alertaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_datosLayout.createSequentialGroup()
                                .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jtf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbl_alertaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_tipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_alertaTipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_area, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jlbl_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jbtn_volver.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtn_volver.setText("VOLVER");
        jbtn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_crud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_crud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Controla el boton volver
     *
     * @param evt
     */
    private void jbtn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverActionPerformed
        //Inhabilita Botones
        habilitarTodosLosBotones(false);

        //limpia todos los campos
        limpiarTodosLosCampos();

        //Habilita el Arbol de seleccion        
        JFramePrincipal.getArbolModulos().setEnabled(true);
        JFramePrincipal.getjPanelContenido().removeAll();
        JFramePrincipal.getjPanelContenido().repaint();
    }//GEN-LAST:event_jbtn_volverActionPerformed

    /**
     * Controla el boton cancelar
     *
     * @param evt
     */
    private void jbtn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelarActionPerformed
        //Actualizar el TableModel con la lista del controlador
        this.tablaEmpleadoModelo.setOperadores(this.controlador.buscarTodosLosOperadores());

        //Refrescar el modelo en la tabla
        this.tablaEmpleadoModelo.fireTableDataChanged();

        limpiarTodosLosCampos();
        habilitarTodosLosCampos(false);
        habilitarTodosLosBotones(false);

        this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarCampo(true, this.jtf_buscarEmpleado);

        this.operadorSeleccionado = null;

        this.jtb_empleado.setEnabled(true);

        this.jlbl_alertaNombre.setIcon(null);
        this.jlbl_alertaApellido.setIcon(null);
        this.jlbl_alertaDNI.setIcon(null);

        this.jlbl_mensaje.setText("");
    }//GEN-LAST:event_jbtn_cancelarActionPerformed

    /**
     * Controla el boton modificar
     *
     * @param evt
     */
    private void jbtn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_modificarActionPerformed
        this.crud = "modificar";
        habilitarTodosLosBotones(false);
        habilitarTodosLosCampos(true);
        this.validador.habilitarBoton(false, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_aceptar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_cancelar, Color.red, Color.WHITE, null, null);
        this.validador.habilitarBoton(false, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarCampo(false, this.jtf_buscarEmpleado);

        this.jtb_empleado.setEnabled(false);
        cargarTiposDeEmpleado();
        cargarAreas();
        this.jcb_tipoEmpleado.setSelectedItem(this.operadorSeleccionado.getUnTipoOperador());
        this.jcb_area.setSelectedItem(this.operadorSeleccionado.getUnDepartamentoA());
    }//GEN-LAST:event_jbtn_modificarActionPerformed

    /**
     * Controla el boton aceptar si se presiono el boton agregar, llama a la
     * función agregar si se presiono el boton modificar, llama a la función
     * modificar si se presiono el boton eliminar, llama a la función eliminar
     *
     * @param evt
     */
    private void jbtn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_aceptarActionPerformed
        int opcion = 0;
        if (crud.equals("agregar")) {
            opcion = JOptionPane.showConfirmDialog(null, "Realmente desea Agregar la persona", "Confirmar Creación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (opcion == 0) {
                agregar();
            } else {
                //Actualizar el TableModel con la lista del controlador
                this.tablaEmpleadoModelo.setOperadores(this.controlador.buscarTodosLosOperadores());

                //Refrescar el modelo en la tabla
                this.tablaEmpleadoModelo.fireTableDataChanged();

                limpiarTodosLosCampos();
                habilitarTodosLosCampos(false);
                habilitarTodosLosBotones(false);

                this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarCampo(true, this.jtf_buscarEmpleado);

                this.operadorSeleccionado = null;

                this.jtb_empleado.setEnabled(true);

                this.jlbl_alertaNombre.setIcon(null);
                this.jlbl_alertaApellido.setIcon(null);
                this.jlbl_alertaDNI.setIcon(null);

                this.jlbl_mensaje.setText("");
            }
        }

        if (crud.equals("modificar")) {
            opcion = JOptionPane.showConfirmDialog(null, "Realmente desea Modificar la persona", "Confirmar Modificación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (opcion == 0) {
                try {
                    modificar();
                } catch (Exception ex) {
                    Logger.getLogger(PanelEmpleado.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                //Actualizar el TableModel con la lista del controlador
                this.tablaEmpleadoModelo.setOperadores(this.controlador.buscarTodosLosOperadores());

                //Refrescar el modelo en la tabla
                this.tablaEmpleadoModelo.fireTableDataChanged();

                limpiarTodosLosCampos();
                habilitarTodosLosCampos(false);
                habilitarTodosLosBotones(false);

                this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarCampo(true, this.jtf_buscarEmpleado);

                this.operadorSeleccionado = null;

                this.jtb_empleado.setEnabled(true);

                this.jlbl_alertaNombre.setIcon(null);
                this.jlbl_alertaApellido.setIcon(null);
                this.jlbl_alertaDNI.setIcon(null);

                this.jlbl_mensaje.setText("");
            }
        }
        if (crud.equals("eliminar")) {
            opcion = JOptionPane.showConfirmDialog(null, "Realmente desea eliminar la persona", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (opcion == 0) {

                try {
                    if (controlador.eliminarOperador(operadorSeleccionado)) {
                        opcion = JOptionPane.showConfirmDialog(null, "La eliminación se realizo con exito", "Persona Eliminada", JOptionPane.CLOSED_OPTION, JOptionPane.QUESTION_MESSAGE);
                    } else {
                        //No se pudo eliminar
                        opcion = JOptionPane.showConfirmDialog(null, "Persona asociada a registros", "Error Eliminación", JOptionPane.CLOSED_OPTION, JOptionPane.QUESTION_MESSAGE);
                    }
                    //Actualizar el TableModel con la lista del controlador
                    this.tablaEmpleadoModelo.setOperadores(this.controlador.buscarTodosLosOperadores());

                    //Refrescar el modelo en la tabla
                    this.tablaEmpleadoModelo.fireTableDataChanged();

                    limpiarTodosLosCampos();
                    habilitarTodosLosCampos(false);
                    habilitarTodosLosBotones(false);

                    this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
                    this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
                    this.validador.habilitarCampo(true, this.jtf_buscarEmpleado);

                    this.operadorSeleccionado = null;

                    this.jtb_empleado.setEnabled(true);

                    this.jlbl_alertaNombre.setIcon(null);
                    this.jlbl_alertaApellido.setIcon(null);
                    this.jlbl_alertaDNI.setIcon(null);

                    this.jlbl_mensaje.setText("");

                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(PanelEmpleado.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                //Actualizar el TableModel con la lista del controlador
                this.tablaEmpleadoModelo.setOperadores(this.controlador.buscarTodosLosOperadores());

                //Refrescar el modelo en la tabla
                this.tablaEmpleadoModelo.fireTableDataChanged();

                limpiarTodosLosCampos();
                habilitarTodosLosCampos(false);
                habilitarTodosLosBotones(false);

                this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarCampo(true, this.jtf_buscarEmpleado);

                this.operadorSeleccionado = null;

                this.jtb_empleado.setEnabled(true);

                this.jlbl_alertaNombre.setIcon(null);
                this.jlbl_alertaApellido.setIcon(null);
                this.jlbl_alertaDNI.setIcon(null);

                this.jlbl_mensaje.setText("");
            }
        }


    }//GEN-LAST:event_jbtn_aceptarActionPerformed

    /**
     * Controla el boton Listar
     *
     * @param evt
     */
    private void jbtn_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_listarActionPerformed
        //Actualizar el TableModel con la lista del controlador
        this.tablaEmpleadoModelo.setOperadores(this.controlador.buscarTodosLosOperadores());

        //Refrescar el modelo en la tabla
        this.tablaEmpleadoModelo.fireTableDataChanged();

        limpiarTodosLosCampos();
        habilitarTodosLosCampos(false);
        habilitarTodosLosBotones(false);

        this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarCampo(true, this.jtf_buscarEmpleado);

        this.operadorSeleccionado = null;

    }//GEN-LAST:event_jbtn_listarActionPerformed

    /**
     * Controla el boton agregar
     *
     * @param evt
     */
    private void jbtn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarActionPerformed
        this.crud = "agregar";
        this.validador.limpiarCampo(this.jtf_nombre);
        this.validador.limpiarCampo(this.jtf_apellido);
        this.validador.limpiarCampo(this.jtf_dni);
        this.validador.limpiarCampo(this.jtf_buscarEmpleado);
        this.jcb_tipoEmpleado.removeAllItems();
        this.jcb_area.removeAllItems();
        habilitarTodosLosBotones(false);
        habilitarTodosLosCampos(true);
        this.validador.habilitarBoton(false, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_aceptar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_cancelar, Color.red, Color.WHITE, null, null);
        this.validador.habilitarBoton(false, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarCampo(false, this.jtf_buscarEmpleado);

        this.jtb_empleado.setEnabled(false);
        cargarTiposDeEmpleado();
        cargarAreas();

    }//GEN-LAST:event_jbtn_agregarActionPerformed

    /**
     * Controla el Foco del JTextFiel buscar persona
     *
     * @param evt
     */
    private void jtf_buscarEmpleadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_buscarEmpleadoFocusGained
        if (this.jtf_buscarEmpleado.isEditable()) {
            this.tablaEmpleadoModelo.setOperadores(this.controlador.buscarTodosLosOperadores());

            //Refrescar el modelo en la tabla
            this.tablaEmpleadoModelo.fireTableDataChanged();

            limpiarTodosLosCampos();
            habilitarTodosLosCampos(false);
            habilitarTodosLosBotones(false);

            this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
            this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
            this.validador.habilitarCampo(true, this.jtf_buscarEmpleado);

            this.operadorSeleccionado = null;

            this.jtb_empleado.setEnabled(true);

            this.jlbl_alertaNombre.setIcon(null);
            this.jlbl_alertaApellido.setIcon(null);
            this.jlbl_alertaDNI.setIcon(null);

            this.jlbl_mensaje.setText("");
        }
    }//GEN-LAST:event_jtf_buscarEmpleadoFocusGained

    /**
     * Escucha si en el JTextFiel buscar persona se presionan teclas
     *
     * @param evt
     */
    private void jtf_buscarEmpleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_buscarEmpleadoKeyReleased
        if (this.jtf_buscarEmpleado.isEditable()) {
            //Actualizar el TableModel con la lista del controlador
            this.tablaEmpleadoModelo.setOperadores(this.controlador.buscarOperadoresPorDNI(this.jtf_buscarEmpleado.getText()));

            //Refrescar el modelo en la tabla
            this.tablaEmpleadoModelo.fireTableDataChanged();
        }
    }//GEN-LAST:event_jtf_buscarEmpleadoKeyReleased

    /**
     * Controla el boton eliminar
     *
     * @param evt
     */
    private void jbtn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_eliminarActionPerformed
        this.crud = "eliminar";
        habilitarTodosLosBotones(false);
        habilitarTodosLosCampos(false);
        this.validador.habilitarBoton(false, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_aceptar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_cancelar, Color.red, Color.WHITE, null, null);
        this.validador.habilitarBoton(false, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarCampo(false, this.jtf_buscarEmpleado);

        this.jtb_empleado.setEnabled(false);
    }//GEN-LAST:event_jbtn_eliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel_crud;
    private javax.swing.JPanel jPanel_datos;
    private javax.swing.JScrollPane jScrollPaneTabla;
    private javax.swing.JButton jbtn_aceptar;
    private javax.swing.JButton jbtn_agregar;
    private javax.swing.JButton jbtn_cancelar;
    private javax.swing.JButton jbtn_eliminar;
    private javax.swing.JButton jbtn_listar;
    private javax.swing.JButton jbtn_modificar;
    private javax.swing.JButton jbtn_volver;
    private javax.swing.JComboBox<String> jcb_area;
    private javax.swing.JComboBox<String> jcb_tipoEmpleado;
    private javax.swing.JLabel jlbl_alertaApellido;
    private javax.swing.JLabel jlbl_alertaDNI;
    private javax.swing.JLabel jlbl_alertaNombre;
    private javax.swing.JLabel jlbl_alertaTipoPersona;
    private javax.swing.JLabel jlbl_mensaje;
    private javax.swing.JTable jtb_empleado;
    private javax.swing.JTextField jtf_apellido;
    private javax.swing.JTextField jtf_buscarEmpleado;
    private javax.swing.JTextField jtf_dni;
    private javax.swing.JTextField jtf_nombre;
    // End of variables declaration//GEN-END:variables

    //--------------------------------------------------------------------------
    //--------------------------Metodos Implementados---------------------------
    //--------------------------------------------------------------------------
    @Override
    public void habilitarTodosLosCampos(boolean estado) {
        this.validador.habilitarCampo(estado, this.jtf_nombre);
        this.validador.habilitarCampo(estado, this.jtf_apellido);
        this.validador.habilitarCampo(estado, this.jtf_dni);
        this.validador.habilitarCampo(estado, this.jtf_buscarEmpleado);
        this.validador.habilitarCombobox(estado, this.jcb_tipoEmpleado);
        this.validador.habilitarCombobox(estado, this.jcb_area);
    }

    @Override
    public void limpiarTodosLosCampos() {
        this.validador.limpiarCampo(this.jtf_nombre);
        this.validador.limpiarCampo(this.jtf_apellido);
        this.validador.limpiarCampo(this.jtf_dni);
        this.validador.limpiarCampo(this.jtf_buscarEmpleado);
        this.jcb_tipoEmpleado.removeAllItems();
        this.jcb_area.removeAllItems();
    }

    @Override
    public void habilitarTodosLosBotones(boolean estado) {
        this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(estado, this.jbtn_aceptar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(estado, this.jbtn_cancelar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(estado, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(estado, this.jbtn_eliminar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(estado, this.jbtn_modificar, new Color(30, 132, 73), Color.WHITE, null, null);
    }

    //--------------------------------------------------------------------------
    //--------------------------Metodos Getters y Settes------------------------
    //--------------------------------------------------------------------------
    public javax.swing.JButton getJbtn_aceptar() {
        return this.jbtn_aceptar;
    }

    public javax.swing.JButton getJbtn_agregar() {
        return this.jbtn_agregar;
    }

    public javax.swing.JButton getJbtn_cancelar() {
        return this.jbtn_cancelar;
    }

    public javax.swing.JButton getJbtn_eliminar() {
        return this.jbtn_eliminar;
    }

    public javax.swing.JButton getJbtn_modificar() {
        return this.jbtn_modificar;
    }

    public ValidadorDeCampos getValidador() {
        return this.validador;
    }

    public javax.swing.JTextField getJtf_buscarPersona() {
        return this.jtf_buscarEmpleado;
    }

    public Operador getOperadorSeleccionado() {
        return this.operadorSeleccionado;
    }

    public void setOperadorSeleccionado(Operador operadorSeleccionado) {
        this.operadorSeleccionado = operadorSeleccionado;
    }

    //--------------------------------------------------------------------------
    //--------------------------Metodos Adicionales-----------------------------
    //--------------------------------------------------------------------------
    /**
     * Carga los tipos de persona el el JComboBox tipo de persona
     */
    public void cargarTiposDeEmpleado() {
        DefaultComboBoxModel mdl = new DefaultComboBoxModel(this.controlador.buscarTodosLosTiposDeoperadores());
        this.jcb_tipoEmpleado.setModel(mdl);
    }
    
    /**
     * Carga los tipos de persona el el JComboBox tipo de persona
     */
    public void cargarAreas() {
        DefaultComboBoxModel mdl = new DefaultComboBoxModel(this.controlador.buscarTodasLosDepartamentos());
        this.jcb_area.setModel(mdl);
    }

    /**
     * Selecciona una fila de la tabla, devolviendo un objeto Persona
     */
    public void seleccionarEmpleado() {
        //obtiene el indice de la fila seleccionada en la tabla de operadores
        int filaSeleccionada = this.jtb_empleado.getSelectedRow();
        // si la fila esta seleccionada, seteamos la persona auxiliar, llamando al modelo de tabla
        if (filaSeleccionada >= 0) {
            this.operadorSeleccionado = this.tablaEmpleadoModelo.obtenerOperadorEn(filaSeleccionada);
            this.jtf_nombre.setText(this.operadorSeleccionado.getNombre());
            this.jtf_apellido.setText(this.operadorSeleccionado.getApellido());
            this.jtf_dni.setText(this.operadorSeleccionado.getDni());
            this.jcb_tipoEmpleado.removeAllItems();
            this.jcb_tipoEmpleado.addItem(this.operadorSeleccionado.getUnTipoOperador().getDescripcion());
            this.jcb_area.removeAllItems();
            this.jcb_area.addItem(this.operadorSeleccionado.getUnDepartamentoA().getNombre());
        } else {
            this.validador.habilitarBoton(false, this.jbtn_aceptar, new Color(30, 132, 73), Color.WHITE, null, null);
            this.validador.habilitarBoton(true, this.jbtn_eliminar, new Color(30, 132, 73), Color.WHITE, null, null);
            this.validador.habilitarBoton(true, this.jbtn_modificar, new Color(30, 132, 73), Color.WHITE, null, null);
        }
    }

    //--------------------------------------------------------------------------
    //--------------------------Metodos CRUD------------------------------------
    //--------------------------------------------------------------------------
    /**
     * Crea un persona auxiliar y se lo envia al controlador para que persista
     * si el dni ya existe solicita que se ingrese uno diferente
     */
    public void agregar() {
        String mensaje = "";
        Operador nuevoEmpleado = null;
        mensaje = "Completar:";
        if ((!this.jtf_nombre.getText().isEmpty()) && (!this.jtf_apellido.getText().isEmpty()) && (!this.jtf_dni.getText().isEmpty())) {

            nuevoEmpleado = new Operador();
            nuevoEmpleado.setNombre(this.jtf_nombre.getText());
            nuevoEmpleado.setApellido(this.jtf_apellido.getText());
            nuevoEmpleado.setDni(this.jtf_dni.getText());
            nuevoEmpleado.setUnTipoOperador((TipoOperador) this.jcb_tipoEmpleado.getSelectedItem());
            nuevoEmpleado.setUnDepartamentoA((Departamento) this.jcb_area.getSelectedItem());
            this.jlbl_alertaNombre.setIcon(null);
            this.jlbl_alertaApellido.setIcon(null);
            this.jlbl_alertaDNI.setIcon(null);
            this.jlbl_mensaje.setText("");

        } else {
            if (this.jtf_nombre.getText().isEmpty()) {
                this.jlbl_alertaNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/delete.png")));
                mensaje = mensaje + " *Nombre ";
            } else {
                this.jlbl_alertaNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/accept.png")));
            }
            if (this.jtf_apellido.getText().isEmpty()) {
                this.jlbl_alertaApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/delete.png")));
                mensaje = mensaje + " *Apellido ";
            } else {
                this.jlbl_alertaApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/accept.png")));
            }
            if (this.jtf_dni.getText().isEmpty()) {
                this.jlbl_alertaDNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/delete.png")));
                mensaje = mensaje + " *DNI ";
            } else {
                this.jlbl_alertaDNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/accept.png")));
            }
            this.jlbl_mensaje.setText(mensaje);
        }
        if (nuevoEmpleado != null) {
            if (this.controlador.agregarOperador(nuevoEmpleado)) {
                this.jlbl_mensaje.setText("");

                //limpiar campos
                //Actualizar el TableModel con la lista del controlador
                this.tablaEmpleadoModelo.setOperadores(this.controlador.buscarTodosLosOperadores());

                //Refrescar el modelo en la tabla
                this.tablaEmpleadoModelo.fireTableDataChanged();

                limpiarTodosLosCampos();
                habilitarTodosLosCampos(false);
                habilitarTodosLosBotones(false);

                this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarCampo(true, this.jtf_buscarEmpleado);

                this.jtb_empleado.setEnabled(true);

                this.operadorSeleccionado = null;

                this.jtb_empleado.getSelectionModel().setSelectionInterval(this.tablaEmpleadoModelo.getRowCount() - 1, this.tablaEmpleadoModelo.getRowCount() - 1);
                this.tablaEmpleadoModelo.getValueAt(this.tablaEmpleadoModelo.getRowCount() - 1, 0);

                seleccionarEmpleado();

                int selectedRow = jtb_empleado.getSelectedRow();
                Rectangle rect = jtb_empleado.getCellRect(selectedRow, 0, true);
                jScrollPaneTabla.getViewport().scrollRectToVisible(rect);
                crud = "";
            } else {
                this.jlbl_alertaDNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/delete.png")));
                mensaje = mensaje + " *El DNI ya existe, ingrese otro";
                this.jlbl_mensaje.setText(mensaje);
            }
        }

    }

    /**
     * Modifica una persona existente
     *
     * @throws java.lang.Exception
     */
    public void modificar() throws Exception {
        String mensaje = "";
        Operador nuevoEmpleado = null;
        mensaje = "Completar:";
        if ((!this.jtf_nombre.getText().isEmpty()) && (!this.jtf_apellido.getText().isEmpty()) && (!this.jtf_dni.getText().isEmpty())) {

            nuevoEmpleado = new Operador();
            nuevoEmpleado.setNombre(this.jtf_nombre.getText());
            nuevoEmpleado.setApellido(this.jtf_apellido.getText());
            nuevoEmpleado.setDni(this.jtf_dni.getText());
            nuevoEmpleado.setUnTipoOperador((TipoOperador) this.jcb_tipoEmpleado.getSelectedItem());
            nuevoEmpleado.setUnDepartamentoA((Departamento) this.jcb_area.getSelectedItem());
            this.jlbl_alertaNombre.setIcon(null);
            this.jlbl_alertaApellido.setIcon(null);
            this.jlbl_alertaDNI.setIcon(null);
            this.jlbl_mensaje.setText("");

        } else {
            if (this.jtf_nombre.getText().isEmpty()) {
                this.jlbl_alertaNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/delete.png")));
                mensaje = mensaje + " *Nombre ";
            } else {
                this.jlbl_alertaNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/accept.png")));
            }
            if (this.jtf_apellido.getText().isEmpty()) {
                this.jlbl_alertaApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/delete.png")));
                mensaje = mensaje + " *Apellido ";
            } else {
                this.jlbl_alertaApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/accept.png")));
            }
            if (this.jtf_dni.getText().isEmpty()) {
                this.jlbl_alertaDNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/delete.png")));
                mensaje = mensaje + " *DNI ";
            } else {
                this.jlbl_alertaDNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/accept.png")));
            }
            this.jlbl_mensaje.setText(mensaje);
        }
        if (nuevoEmpleado != null) {
            if (this.controlador.modificarOperador(operadorSeleccionado, nuevoEmpleado)) {

                this.jlbl_mensaje.setText("");

                //limpiar campos
                //Actualizar el TableModel con la lista del controlador
                this.tablaEmpleadoModelo.setOperadores(this.controlador.buscarTodosLosOperadores());

                //Refrescar el modelo en la tabla
                this.tablaEmpleadoModelo.fireTableDataChanged();

                limpiarTodosLosCampos();
                habilitarTodosLosCampos(false);
                habilitarTodosLosBotones(false);

                this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
                this.validador.habilitarCampo(true, this.jtf_buscarEmpleado);

                this.jtb_empleado.setEnabled(true);

                this.jtb_empleado.getSelectionModel().setSelectionInterval(this.tablaEmpleadoModelo.buscarFilaOperador(operadorSeleccionado) - 1, this.tablaEmpleadoModelo.buscarFilaOperador(operadorSeleccionado) - 1);

                seleccionarEmpleado();

                int selectedRow = jtb_empleado.getSelectedRow();
                Rectangle rect = jtb_empleado.getCellRect(selectedRow, 0, true);
                jScrollPaneTabla.getViewport().scrollRectToVisible(rect);
                crud = "";
            } else {
                this.jlbl_alertaDNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png/16x16/delete.png")));
                mensaje = mensaje + " *El DNI ya existe, ingrese otro";
                this.jlbl_mensaje.setText(mensaje);
            }

        }
    }

    /**
     * Elimina una persona existente
     *
     * @throws java.sql.SQLIntegrityConstraintViolationException
     */
    public void eliminar() throws SQLIntegrityConstraintViolationException, SQLException {

        try {
            controlador.eliminarOperador(operadorSeleccionado);
            this.jlbl_mensaje.setText("");

            //limpiar campos
            //Actualizar el TableModel con la lista del controlador
            this.tablaEmpleadoModelo.setOperadores(this.controlador.buscarTodosLosOperadores());

            //Refrescar el modelo en la tabla
            this.tablaEmpleadoModelo.fireTableDataChanged();

            limpiarTodosLosCampos();
            habilitarTodosLosCampos(false);
            habilitarTodosLosBotones(false);

            this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
            this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
            this.validador.habilitarCampo(true, this.jtf_buscarEmpleado);

            this.jtb_empleado.setEnabled(true);

            this.operadorSeleccionado = null;

            this.jtb_empleado.getSelectionModel().setSelectionInterval(this.tablaEmpleadoModelo.getRowCount() - 1, this.tablaEmpleadoModelo.getRowCount() - 1);
            this.tablaEmpleadoModelo.getValueAt(this.tablaEmpleadoModelo.getRowCount() - 1, 0);

            seleccionarEmpleado();

            int selectedRow = jtb_empleado.getSelectedRow();
            Rectangle rect = jtb_empleado.getCellRect(selectedRow, 0, true);
            jScrollPaneTabla.getViewport().scrollRectToVisible(rect);
            crud = "";
        } catch (NonexistentEntityException ex) {
            //agregar mensaje que la persona esta asociada
            JOptionPane.showConfirmDialog(null, "Posee registros asociados", "Error Eliminación", JOptionPane.CLOSED_OPTION, JOptionPane.QUESTION_MESSAGE);

        }

    }
}
